name: Deploy on Heroku

on:
  push:
    branches:
      - heroku-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'kitchatapp'
          heroku_email: 'contact@alexcloudstar.com'
